### PR TITLE
[etc] docs: Add English version of README

### PR DESCRIPTION
**Pull request by bzantium**
- Add English README and Supported Corpus Type
- fix typo Semi -> Self

Refs: #63

### CODE REVIEW

**Review by seopbo — APPROVED** [review]
Look good to me. Thanks for your contribution @bzantium 🤗

**Review by seopbo — COMMENTED** [review]
Can we change default `README.md` into english ver? How do you think about that? to: @bzantium

**Comment by bzantium** [comment]
> Can we change default `README.md` into english ver? How do you think about that? to: @bzantium

I agree with you. Let's follow global standard.

**Comment by seopbo** [comment]
> > Can we change default `README.md` into english ver? How do you think about that? to: @bzantium
> 
> I agree with you. Let's follow global standard.

a...amazing 😇

**Review by monologg — APPROVED** [review]

**Pull request merged**
